### PR TITLE
Transaction URI Scheme

### PR DESCRIPTION
**Pull request by dgarcia360**

### CODE REVIEW

**Comment by aleixmorgadas** [comment]
Please, merge this PR as enough stable NIP. I think we can iterate it later, or propose a new NIP that overrides this in case we find something better.

**Comment by aleixmorgadas** [comment]
Firefox has some limitations adding the protocol `nem://`, I suggest `web-nem://` be also valid in this URI Schema definition.

Links of interest:
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/protocol_handlers
- https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler

**Comment by dgarcia360** [comment]
@aleixmorgadas Good point, adding the suggestion to the NIP. Hopefully someday "nem" would be a permitted scheme ^^

**Comment by dgarcia360** [comment]
@aleixmorgadas I'm going to do a gist with some examples, I'll post it here later.

``TS/JS library to parse URI Schemas into valid Transactions`` It could be a really light library once the SDK implements the [following functions](https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/56).

**Pull request merged**
